### PR TITLE
Implement archive re-upload

### LINKED ISSUE #113: Users should be able to upload recordings into archives
This feature was present in the old Angular client and has not yet been ported to the React client.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #113

### CODE REVIEW

**Comment by vic-ma** [comment]
When I run CJFR as a local process, I don't see CJFR in targets anymore. I'm not sure if my problem is the same as @jiekang's, but the first commit where it stopped working for me is rh-jmc-team/container-jfr#209. Is there a new flag or setting that needs to be set, to have the local process work with the JMX auth changes?

Also, I forget but are we supposed to be able to access a `run.sh` CJFR with the web-client? In this case, even if I use a really old commit, I don't see CJFR in the targets. If we are supposed to, then there's probably something wrong with my setup.

**Comment by jiekang** [comment]
I don't see targets in local process mode either. I do see targets when using run.sh, though I still haven't figured out my CORS issue that happens after that for downloading recordings, etc.

**Comment by andrewazores** [comment]
> When I run CJFR as a local process, I don't see CJFR in targets anymore. I'm not sure if my problem is the same as @jiekang's, but the first commit where it stopped working for me is [rh-jmc-team/container-jfr#209](https://github.com/rh-jmc-team/container-jfr/pull/209). Is there a new flag or setting that needs to be set, to have the local process work with the JMX auth changes?

You are probably seeing the results of this excerpt:

> The SelfDisoveryPlatformClient is also removed and JDP autodiscovery is enabled instead so that the ContainerJFR instance can use JDP to discover itself within its container in a more uniform manner, providing itself with its own JMXServiceURL and Main-Class name. In environments where JDP autodiscovery is not used, ex. Kubernetes/OpenShift, this also has the net effect of preventing the self-connection list item from appearing in the discovered targets list.

If you are running as a local process with `mvn exec:java`, you must also include the `-Dcom.sun.management.jmxremote.autodiscovery=true` JVM flag to turn on JDP, which will in turn allow ContainerJFR to discover itself. The "This ContainerJFR" entry was provided by the `SelfDiscoveryPlatformClient`. Now, with JDP enabled and running as a local process or in Podman (`run.sh`), you should instead see some JMX Service URL representing ContainerJFR itself instead. JDP is asynchronous, so if it doesn't appear give it a couple of seconds and press the refresh icon/retry your query.

FWIW I would recommend to normally run with something like `mvn clean package && sh run.sh`, since `run.sh` should be kept up-to-date with whatever configuration is needed to run correctly, so you don't need to worry about setting additional JVM flags or environment variables.

> 
> Also, I forget but are we supposed to be able to access a `run.sh` CJFR with the web-client? In this case, even if I use a really old commit, I don't see CJFR in the targets. If we are supposed to, then there's probably something wrong with my setup.

I'm assuming you mean connecting to a ContainerJFR backed run using `run.sh` from a web-client run using `npm run start:dev`? That should work perfectly fine, just be sure to export `CONTAINER_JFR_CORS_ORIGIN=http://localhost:9000` before you `run.sh`.

**Comment by andrewazores** [comment]
> I don't see targets in local process mode either. I do see targets when using run.sh, though I still haven't figured out my CORS issue that happens after that for downloading recordings, etc.

This one is weird. I'm not sure why requests for targets would pass CORS and other requests might not. I know we talked about `CONTAINER_JFR_LISTEN_PORT` before and how you believed that to be conflicting with another service, although that port and its env var are unused when ContainerJFR is in websocket mode (as it is normally and how it must be if you're able to use the web-client at all). Do you have `CONTAINER_JFR_WEB_PORT`, `CONTAINER_JFR_EXT_WEB_PORT`, `CONTAINER_JFR_WEB_HOST`, or any other environment variables set?

**Comment by jiekang** [comment]
> > When I run CJFR as a local process, I don't see CJFR in targets anymore. I'm not sure if my problem is the same as @jiekang's, but the first commit where it stopped working for me is [rh-jmc-team/container-jfr#209](https://github.com/rh-jmc-team/container-jfr/pull/209). Is there a new flag or setting that needs to be set, to have the local process work with the JMX auth changes?
> 
> You are probably seeing the results of this excerpt:
> 
> > The SelfDisoveryPlatformClient is also removed and JDP autodiscovery is enabled instead so that the ContainerJFR instance can use JDP to discover itself within its container in a more uniform manner, providing itself with its own JMXServiceURL and Main-Class name. In environments where JDP autodiscovery is not used, ex. Kubernetes/OpenShift, this also has the net effect of preventing the self-connection list item from appearing in the discovered targets list.
> 
> If you are running as a local process with `mvn exec:java`, you must also include the `-Dcom.sun.management.jmxremote.autodiscovery=true` JVM flag to turn on JDP, which will in turn allow ContainerJFR to discover itself. The "This ContainerJFR" entry was provided by the `SelfDiscoveryPlatformClient`. Now, with JDP enabled and running as a local process or in Podman (`run.sh`), you should instead see some JMX Service URL representing ContainerJFR itself instead. JDP is asynchronous, so if it doesn't appear give it a couple of seconds and press the refresh icon/retry your query.
> 

Ah; the README command has been updated by I've still been running off my old reverse-search version. Nice intuition to find this issue! The local mode now discovers itself, but I still get 405s :|

**Comment by vic-ma** [comment]
>If you are running as a local process with mvn exec:java, you must also include the -Dcom.sun.management.jmxremote.autodiscovery=true

Ah, yeah that fixed it for me.

>I'm assuming you mean connecting to a ContainerJFR backend run using run.sh from a web-client run using npm run start:dev?

I've confused myself a bit going back and forth between commits, so I'll just focus on what happens on main.

I was just using `localhost:8181`, but even if I do `CONTAINER_JFR_CORS_ORIGIN=http://localhost:9000 sh run.sh -it` and start a separate web client and go to `localhost:9000`, it isn't working. I am getting these exceptions in logs when I open the web client (either `8181` or `9000`):
```
[INFO] Max concurrent WebSocket connections: 2
> [INFO] (127.0.0.1:38294): GET /api/v1/clienturl 200 106ms
[INFO] java.io.IOException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.lambda$checkUri$0(HealthGetHandler.java:133)
	at io.vertx.ext.web.client.impl.HttpContext.handleFailure(HttpContext.java:309)
...
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:3000
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

...

[INFO] java.io.IOException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:3000
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.lambda$checkUri$0(HealthGetHandler.java:133)
	at io.vertx.ext.web.client.impl.HttpContext.handleFailure(HttpContext.java:309)
...
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:3000
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

...

[INFO] (127.0.0.1:38298): GET /health 200 305ms
[INFO] (127.0.0.1:38306): POST /api/v1/auth 200 1ms
[INFO] Connected remote client 127.0.0.1:38314
[INFO] (127.0.0.1:38314): CMD {"id":"ncjopWiRWfVUeBirjnfMX","command":"list-saved","args":[]}
[INFO] (127.0.0.1:38314): CMD {"id":"7etdhjRR4AYfDmBhb3G4P","command":"scan-targets","args":[]}
```
And in the webpage, I can't click on the "Select Target..." button. The errors mention the health handler, but Grafana and jfr-datsource are both running and should be working; I tested uploading with a local process and it worked. Although we said that the upload shouldn't work with the run script anyway since it's in a container and grafana isn't, right?

Here is the network monitor:

openingweb

**Comment by andrewazores** [comment]
Why are you doing `sh run.sh -it`? That puts ContainerJFR into interactive mode, so it runs the interactive executor rather than the WebSocket executor. In this case I don't believe the server even starts listening for incoming WS connections, and if it does, there is nothing on the ContainerJFR side there to respond to any messages sent (including connection handshake messages). Try again without the `-it` argument.

**Comment by vic-ma** [comment]
Yeah, removing `-it` fixed it. I haven't used the run script in a long time since I've been working on `upload-recording`, so I forgot :|

**Comment by andrewazores** [comment]
Rebased.

**Comment by vic-ma** [comment]
In main (as well as here since the rebase), I can't seem to upload an archived recording anymore, after #110. Regular recording uploads still work. Archived recording uploads work on the commit before.

```
Danger alert:Request failed (Status 404)
Not Found
```

```
[WARN] io.vertx.ext.web.handler.impl.HttpStatusException: Not Found
Caused by: com.redhat.rhjmc.containerjfr.net.internal.reports.ReportService$RecordingNotFoundException: Recording victor-work_foo1_20200817T145623Z.jfr not found in target service:jmx:rmi:///jndi/rmi://victor-work:9091/jmxrmi
	at com.redhat.rhjmc.containerjfr.net.web.handlers.TargetRecordingUploadPostHandler.lambda$doPost$0(TargetRecordingUploadPostHandler.java:135)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.redhat.rhjmc.containerjfr.net.web.handlers.TargetRecordingUploadPostHandler.lambda$doPost$1(TargetRecordingUploadPostHandler.java:133)
	at com.redhat.rhjmc.containerjfr.net.TargetConnectionManager.executeConnectedTask(TargetConnectionManager.java:86)
...
```

**Comment by andrewazores** [comment]
Ah, yea I see the cause of the bug. Good catch. I'll fix that separately.

**Comment by vic-ma** [comment]
Could you rebase again, and I'll re-review with the fixed archive upload?

**Comment by vic-ma** [comment]
On an unrelated note, I was thinking, when a download-recording fails (e.g., due to the recording being deleted from the backend), would it be better for the download not to go off at all? Since #120 added an error message popup for when it does fail, so the user doesn't have to rely on the file contents saying the file was deleted. Or is it good that it always returns a file so it's consistent?

**Comment by andrewazores** [comment]
No, I agree that it would be better to not cause a "X not found" file download to occur. That should instead just result in an error notification being shown.

**Comment by andrewazores** [comment]
@vic-ma would you like to take a look at that bug? It's a pretty easy one.

**Comment by vic-ma** [comment]
Sure.

**Pull request merged**
